USE [master]
GO

/****** Object:  Database [MoviesDb]    Script Date: 24/03/2020 20:56:04 ******/
CREATE DATABASE [MoviesDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoviesDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoviesDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoviesDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoviesDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoviesDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoviesDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoviesDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoviesDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoviesDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoviesDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoviesDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoviesDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoviesDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoviesDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoviesDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoviesDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoviesDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoviesDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoviesDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoviesDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoviesDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoviesDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoviesDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoviesDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoviesDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoviesDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MoviesDb] SET  MULTI_USER 
GO

ALTER DATABASE [MoviesDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoviesDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoviesDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoviesDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoviesDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoviesDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoviesDb] SET  READ_WRITE 
GO


